### ISSUE TITLE
TDFTest.cls does not compile.

### ISSUE THREAD

**Issue by antnoley** [benahm/TDF#3]
TDFTest.cls does not compile.
Result: [OPERATION FAILED]: classes/TDFTest.cls: Method does not exist or incorrect signature: void createSObject(String) from the type TDF (Line: 25, Column: 22)
classes/TDFTest.cls: Method does not exist or incorrect signature: void createSObject(String, Map<String,Object>) from the type TDF (Line: 29, Column: 22)
classes/TDFTest.cls: Method does not exist or incorrect signature: void createSObject(String, Map<String,Object>) from the type TDF (Line: 41, Column: 24)...

**Comment by benahm** [comment]
Hello

TDFTest was outdated, I just updated it now with the latest tests for the TDF class
TDFTest should run successfully to have around 97% test coverage for the TDF 

(Note that I also updated the TDF class)

but as explained in the https://github.com/benahm/TDF/blob/master/docs/USAGE.md  TDFTest is not required, I am using those tests in order to make sure that I don't break the TDF class when I'm adding new features 

Thanks for logging these issues

**Comment by antnoley** [comment]
TDFTest.cls now compiles when the TDF.PERSON_ACCOUNT_IS_ENABLED is public or has the @TestVisible notation.
